### ISSUE TITLE
Lower Minimum SDK

### ISSUE THREAD

**Issue by Fabi755** [side-codes/andColorPicker#58]
**Is your feature request related to a problem? Please describe.**
Current minimum SDK is set to API 21. For example my app supports back to API 19. I can't use this library :(

**Describe the solution you'd like**
Support lower API versions.

**Comment by dummyco** [comment]
@Fabi755 I've tried to cover all the backward compatibility cases and released a 0.4.0 version in #61.
`implementation "codes.side:andcolorpicker:0.4.0"`
Feel free to report any new issues and feature requests!
